# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backrest < Formula
  desc ""
  homepage "https://github.com/garethgeorge/backrest"
  version "0.17.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garethgeorge/backrest/releases/download/v0.17.0/backrest_Darwin_x86_64.tar.gz"
      sha256 "a4c694ffbbd69aa7a56519d653519bc529c0a0883be808dd0b382e6e24190c0c"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garethgeorge/backrest/releases/download/v0.17.0/backrest_Darwin_arm64.tar.gz"
      sha256 "29b6d5964c073cf1033f544add87699a0801aa8885ae75868fbef58a063d1e70"

      def install
        bin.install "backrest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garethgeorge/backrest/releases/download/v0.17.0/backrest_Linux_x86_64.tar.gz"
      sha256 "aa45b02fd4145ad1e3004cb852a889af37bed06eeca0f961565701c554be9d9f"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/garethgeorge/backrest/releases/download/v0.17.0/backrest_Linux_armv6.tar.gz"
      sha256 "2d85e141b940656325fd6f58fa25204004d12f13c3381aa436e7e5730b5f6479"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethgeorge/backrest/releases/download/v0.17.0/backrest_Linux_arm64.tar.gz"
      sha256 "d073dd8817c61b09b9b807f112b432d78859df69d6bc44348da4c89357b4deb4"

      def install
        bin.install "backrest"
      end
    end
  end

  plist_options startup: false

  def plist
    <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.backrest</string>
    <key>ProgramArguments</key>
    <array>
    <string>/usr/local/bin/backrest</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/backrest.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/backrest.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>

    EOS
  end
end
