# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backrest < Formula
  desc ""
  homepage "https://github.com/garethgeorge/backrest"
  version "0.17.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Darwin_x86_64.tar.gz"
      sha256 "c65c28db3f8d34fe7ece3a749013fccc48be9a47f835b9dbeaedf029933e8a57"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Darwin_arm64.tar.gz"
      sha256 "b9930604668670efb90be1d13d9208cd6bf4b19ca504db4364e3a547bea02cb0"

      def install
        bin.install "backrest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_x86_64.tar.gz"
      sha256 "a1fbabb9fbc9735f206a11f96a81657c38d0855f1d5bd11d1efb79e7e6060d0b"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_armv6.tar.gz"
      sha256 "8402c567ef6cc327f39548c4002096fc63f168ac01a32f338f7e11935a5c7f57"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_arm64.tar.gz"
      sha256 "5e4668b80b53e1f2170f12b41c9bad85ca67c5b4bcf2b43f5546a03dd6726889"

      def install
        bin.install "backrest"
      end
    end
  end

  service do
    run opt_bin/"backrest"
    error_log_path var/"log/backrest.log"
    log_path var/"log/backrest.log"
  end
end
