# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backrest < Formula
  desc ""
  homepage "https://github.com/garethgeorge/backrest"
  version "0.17.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Darwin_x86_64.tar.gz"
      sha256 "cd91305cde86184018fe0abfc5de90f0f4a395fe4418b38482757414312ba0ba"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Darwin_arm64.tar.gz"
      sha256 "7ac19a7bdc63dc65b1155d7b6f68336eef87f7382e5bb3d915381240cf3f9a72"

      def install
        bin.install "backrest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_x86_64.tar.gz"
      sha256 "3c89708a7d461f5436b1cc5796fdca154997094554ff0e36b36ae832a9b687ad"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_armv6.tar.gz"
      sha256 "482fc6e28208892e8f029b0f2657afc86d08571789f19cee19f99a3f9d234288"

      def install
        bin.install "backrest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmaguire/backrest/releases/download/v0.17.0/backrest_Linux_arm64.tar.gz"
      sha256 "e46c1397063c62aa6ddb332c69c6dd79314f1dca1a5ce74b8b4efe44bc5fa830"

      def install
        bin.install "backrest"
      end
    end
  end

  service do
    backrest
  end
end
